services:
  - type: web
    name: discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        fromService:
          type: secret
          name: discord-token
      - key: CLIENT_ID
        fromService:
          type: secret
          name: client-id
      - key: WORKER_URL
        fromService:
          type: secret
          name: worker-url
      - key: OWNER_ID
        fromService:
          type: secret
          name: owner-id
      - key: GUILD_ID
        fromService:
          type: secret
          name: guild-id
      - key: LOG_CHANNEL_ID
        fromService:
          type: secret
          name: log-channel-id
      - key: STATS_CHANNEL_ID
        value: "1426577469284024420"
      - key: MAX_REQUESTS_PER_USER
        value: "5"
      - key: RATE_LIMIT_WINDOW
        value: "60000"
      - key: DEFAULT_MODEL
        value: "@cf/stabilityai/stable-diffusion-xl-base-1.0"
      - key: DEFAULT_STEPS
        value: "20"
      - key: MAX_STEPS
        value: "50"
      - key: ECONOMY_ENABLED
        value: "true"
      - key: DAILY_AMOUNT
        value: "500"
      - key: WEEKLY_AMOUNT
        value: "2000"
      - key: LEVEL_SYSTEM_ENABLED
        value: "true"
      - key: XP_PER_MESSAGE
        value: "15"
      - key: XP_PER_COMMAND
        value: "25"
      - key: MUSIC_ENABLED
        value: "true"
      - key: TICKET_SYSTEM_ENABLED
        value: "true"
      - key: WEB_DASHBOARD_ENABLED
        value: "true"
      - key: WEB_PORT
        value: "3000"
      - key: MODERATION_ENABLED
        value: "true"
      - key: FUN_COMMANDS_ENABLED
        value: "true"
      - key: NEWS_SYSTEM_ENABLED
        value: "true"
      - key: NEWS_CHANNEL_ID
        value: "1426596564377403442"
      - key: NEWS_UPDATE_INTERVAL
        value: "15"
      - key: NEWS_MAX_POSTS_PER_UPDATE
        value: "3"
      - key: VERIFICATION_SYSTEM_ENABLED
        value: "true"
      - key: VERIFICATION_GUILD_ID
        value: "1402731113239023616"
      - key: UNVERIFIED_ROLE_ID
        value: "1404205796375527536"
      - key: VERIFIED_ROLE_ID
        value: "1404205659922235474"
      - key: VERIFICATION_CHANNEL_ID
        value: "1404204595298963546"
